### PR TITLE
Drop unnecessary XFS reflink patch

### PR DESCRIPTION
**Pull request by rustybird**
This patch turned out to be unnecessary, because mkfs.xfs from xfsprogs
\>= 5.1.0 enables reflink by default:

https://git.kernel.org/pub/scm/fs/xfs/xfsprogs-dev.git/tree/doc/CHANGES?h=v5.1.0#n5

R4.1 installers already have xfsprogs 5.4.0, and R4.0 installers don't
use the forked Blivet.

### CODE REVIEW

**Comment by marmarek** [comment]
> R4.0 installers don't
> use the forked Blivet.

It does: https://github.com/QubesOS/qubes-installer-qubes-os/tree/release4.0/blivet
But the patch isn't there.

**Comment by rustybird** [comment]
Oh indeed. We could move the patch from here to there (if you think it's appropriate for the next R4.0.x release), it applies cleanly on top of Blivet 2.1.11 too.

**Comment by marmarek** [comment]
Since we don't have tests for installation with XFS, I'd say no. But it's possible to change this situation. If you prepare exact list of steps to create partition layout with XFS (it isn't included in automatic partitioning from what I see), I can wrap it as a test on openQA. It needs to be things like "click on this, type that" things. Example test to give you an idea: https://github.com/marmarek/openqa-tests-qubesos/blob/master/tests/install_partitioning_btrfs.pm, arguments for `assert_and_click` or `assert_screen` are naming specific screenshots with marked areas. Testing actual test and preparing those screenshots requires openQA instance which is not straightforward to setup, but I can take care of that part.

**Comment by rustybird** [comment]
The R4.0.4-rc1 installer can do automatic XFS installation, similar to Btrfs installation:

1. In the dropdown, switch from `LVM Thin Provisioning` to `Standard Partition` (instead of `Btrfs`) and choose `Click here to create them automatically.`

2. Click on the `/` root partition on the left (no keyboard shortcut?), which is listed randomly (?!) as the first or the second entry.

3. In the `File System` dropdown on the right, switch from `ext4` to `xfs`.

---

I also tried the R4.1.0-alpha20201014 installer. The `Standard Partition` layout looks bizarre: A very small `/` partition with two additional mystery partitions (somehow listed under `Unknown` instead of `New Qubes OS R4.1.0-alpha20201014 Installation`).

**Comment by marmarek** [comment]
> I also tried the R4.1.0-alpha20201014 installer. The `Standard Partition` layout looks bizarre: A very small `/` partition with two additional mystery partitions (somehow listed under `Unknown` instead of `New Qubes OS R4.1.0-alpha20201014 Installation`).

This is supposed to be small `/` partition + large one for VMs (`/var/lib/qubes` in standard partitions layout), so that running out of space in `/var/lib/qubes` won't affect dom0. But it may be very well that something went wrong.
cc @fepitre 

In fact, it seems we don't have test for "standard partition" layout either.

**Comment by marmarek** [comment]
I can confirm this is broken. The two mystery partitions lack mount point set - this is why they are under "Unknown" section. And the smaller from them should be `/` instead of the tiny one that is additionally created.

**Comment by marmarek** [comment]
XFS installation test: https://openqa.qubes-os.org/tests/14284
Adding the patch to R4.0: https://github.com/QubesOS/qubes-installer-qubes-os/pull/45

**Pull request merged**
